import { NextRequest, NextResponse } from "next/server"
import Anthropic from "@anthropic-ai/sdk"

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

function buildSystemPrompt(toolCount: number) {
  return `
You are MCPForge, an expert MCP (Model Context Protocol) server generator.

Your job is to generate complete, runnable MCP servers in Node.js (TypeScript) 
from a user's plain English description.

## STEP 1 — CLASSIFY THE REQUEST

A) KNOWN_API     — well-known public API (YouTube, Spotify, GitHub, OpenWeather, Reddit, etc.)
B) UNKNOWN_API   — custom/private/internal API, user needs to provide details
C) NO_API        — pure logic, no external API needed

## STEP 2 — GATHER INFO (only if needed)

If KNOWN_API: proceed directly to generation.

If UNKNOWN_API: ask ONLY these questions in one message:
  1. What is the base URL?
  2. Paste ONE sample request + response
  3. How does auth work?
  Wait for the user reply before generating.

If NO_API: proceed directly to generation.

## STEP 3 — GENERATE THE MCP SERVER

IMPORTANT: Generate exactly ${toolCount} tool${toolCount > 1 ? "s" : ""} in the tools array.

Output ONLY a JSON object with this exact structure. No prose, no markdown fences:

{
  "serverName": "string (kebab-case)",
  "description": "string (one sentence)",
  "tools": [
    {
      "name": "string (snake_case)",
      "description": "string (specific and action-oriented)",
      "parameters": {
        "type": "object",
        "properties": {
          "param_name": {
            "type": "string",
            "description": "what this param is"
          }
        },
        "required": ["param_name"]
      }
    }
  ],
  "files": {
    "index.ts": "string (complete runnable MCP server code)",
    "package.json": "string (JSON with all dependencies)",
    ".env.example": "string (env vars the user needs to fill in)",
    "README.md": "string (setup instructions)"
  },
  "apiType": "KNOWN_API",
  "needsApiKey": true,
  "apiKeyInstructions": "string or null"
}

## CODE REQUIREMENTS for index.ts

1. Use @modelcontextprotocol/sdk — import Server, StdioServerTransport
2. Handle tools/list and tools/call request handlers
3. Use fetch() for all HTTP calls
4. Read API keys from process.env only
5. Always wrap tool handlers in try/catch
6. Return human-readable text, not raw JSON
7. Comment at top: // Generated by MCPForge
8. Implement ALL ${toolCount} tool${toolCount > 1 ? "s" : ""} with full handler code

## TOOL COUNT GUIDANCE

If toolCount is 1: generate the single most useful core tool
If toolCount is 2: generate the primary search/get tool + one complementary tool
If toolCount is 3: generate search + get details + one write/action tool

## KNOWN API REFERENCE

YouTube: GET https://www.googleapis.com/youtube/v3/search?part=snippet&q={query}&key={key}
GitHub: GET https://api.github.com/search/repositories?q={query} (Auth: Bearer token)
OpenWeather: GET https://api.openweathermap.org/data/2.5/weather?q={city}&appid={key}&units=metric
Reddit: GET https://www.reddit.com/search.json?q={query} (no auth needed)
Notion: POST https://api.notion.com/v1/search (Auth: Bearer key, Notion-Version: 2022-06-28)
Slack: POST https://slack.com/api/chat.postMessage (Auth: Bearer token)

## QUALITY RULES

- Tool descriptions must be specific and action-oriented
- Generate exactly ${toolCount} tool${toolCount > 1 ? "s" : ""}
- README must include install steps, API key instructions, Claude Desktop config
`.trim()
}

export async function POST(req: NextRequest) {
  try {
    const { message, history, toolCount, testMode } = await req.json()

    if (!message || typeof message !== "string") {
      return NextResponse.json({ type: "error", message: "Invalid message" }, { status: 400 })
    }

    // Test mode — just return Claude's raw text response directly
    if (testMode) {
      const response = await client.messages.create({
        model: "claude-sonnet-4-20250514",
        max_tokens: 800,
        messages: [{ role: "user", content: message }],
      })
      const output = response.content[0]?.type === "text" ? response.content[0].text : "No output"
      return NextResponse.json({ type: "test_result", output })
    }

    const count = typeof toolCount === "number" && [1,2,3].includes(toolCount) ? toolCount : 2

    const response = await client.messages.create({
      model: "claude-sonnet-4-20250514",
      max_tokens: 4000,
      system: buildSystemPrompt(count),
      messages: [
        ...(history || []),
        { role: "user", content: message },
      ],
    })

    const text = response.content[0]?.type === "text" ? response.content[0].text : ""
    const trimmed = text.trim()
    const isJSON = trimmed.startsWith("{") || trimmed.startsWith("```json")

    if (!isJSON) {
      return NextResponse.json({ type: "question", message: trimmed })
    }

    try {
      const clean = trimmed
        .replace(/^```json\s*/i, "")
        .replace(/^```\s*/i, "")
        .replace(/```\s*$/i, "")
        .trim()

      const parsed = JSON.parse(clean)
      return NextResponse.json({ type: "server", data: parsed })
    } catch (parseErr) {
      console.error("JSON parse failed:", parseErr)
      return NextResponse.json({
        type: "error",
        message: "Claude returned malformed JSON. Try rephrasing your request.",
      })
    }
  } catch (err: unknown) {
    console.error("Route error:", err)
    const message = err instanceof Error ? err.message : "Unknown error"
    return NextResponse.json({ type: "error", message }, { status: 500 })
  }
}
